# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

services:
  - MySQL
  - PostgreSQL

env:
  - py27-d16
  - py27-d17
  - py27-d18
  - py27-d19

  - py35-d18
  - py35-d19

before_install:
  - pip install codecov

install:
  - pip install tox "coverage<=4.0" python-coveralls>=2.5 coveralls>=0.5 codecov


script:
  - tox -e $TOXENV -- py.test tests -v --capture=no --cov=django_sysinfo \
    --cov-config=tests/.coveragerc

after_success:
  - codecov
  - coveralls
